// Preserve all three supplied CSVs byte-for-byte in one matching snapshot.
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const Data = require("../DH-FPA/data-model.js");
const directory = path.join(__dirname, "../DH-FPA/data");
function readFile(name) {
  const bytes = fs.readFileSync(path.join(directory, name));
  return { name, sha256: crypto.createHash("sha256").update(bytes).digest("hex"), csv: bytes.toString("utf8") };
}
const weekly = readFile("FPAv2.csv"), summary = readFile("FPFA.csv"), offense = readFile("FPF.csv");
const model = Data.readSource(weekly.csv, { name: weekly.name });
const summaries = Data.readFPFA(summary.csv, { name: summary.name });
const offenses = Data.readOffenses(offense.csv, { name: offense.name });
if (summaries.rows.length !== 32 || model.defenses.some(team => !summaries.byTeam.has(team))) {
  throw new Error("FPFA must contain one summary for each of the 32 defenses.");
}
if (offenses.rows.length !== 32 || Data.TEAMS.some(team => !offenses.byTeam.has(team))) {
  throw new Error("FPF must contain one scoring summary for each of the 32 offenses.");
}
if (summaries.weeks.length && JSON.stringify(summaries.weeks) !== JSON.stringify(model.weeks)) {
  throw new Error("FPFA and FPAv2 must cover the same supplied weeks.");
}
for (const row of summaries.rows) for (const opponent of row.opponents) {
  if (model.gamesByKey.get(`${row.team}|${opponent.week}`)?.offense !== opponent.offense) {
    throw new Error(`FPFA/FPAv2 opponent mismatch: ${row.team}, Week ${opponent.week}.`);
  }
}
const snapshot = { season: 2026, weekly, summary, offense };
const output = "/* Generated by node scripts/sync-data.cjs. Edit the CSV, then regenerate. */\nwindow.FPA_SOURCE = " + JSON.stringify(snapshot).replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029") + ";\n";
fs.writeFileSync(path.join(directory, "2026-weekly.js"), output);
console.log(`Bundled ${model.audit.usedRows} matchup results, ${summaries.rows.length} FPFA defense summaries and ${offenses.rows.length} FPF offense summaries across Weeks ${model.minWeek}–${model.maxWeek}; ${model.audit.excludedRows} rows have no opponent.`);
