// Preserve both supplied CSVs byte-for-byte and bundle one matching source pair.
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const Data = require("../DH-FPA/data-model.js");
const directory = path.join(__dirname, "../DH-FPA/data");
function readFile(name) {
  const bytes = fs.readFileSync(path.join(directory, name));
  return { name, sha256: crypto.createHash("sha256").update(bytes).digest("hex"), csv: bytes.toString("utf8") };
}
const weekly = readFile("FPAv2.csv"), offense = readFile("TSUMS.csv");
const model = Data.readSource(weekly.csv, { name: weekly.name });
const baselines = Data.readOffenses(offense.csv, { name: offense.name });
const snapshot = { season: 2026, weekly, offense };
const output = "/* Generated by node scripts/sync-data.cjs. Edit the CSV, then regenerate. */\nwindow.FPA_SOURCE = " + JSON.stringify(snapshot).replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029") + ";\n";
fs.writeFileSync(path.join(directory, "2026-weekly.js"), output);
console.log(`Bundled ${model.audit.usedRows} matchup results and ${baselines.rows.length} offense baselines across Weeks ${model.minWeek}–${model.maxWeek}; ${model.audit.excludedRows} rows have no opponent.`);
