// Preserve the authoritative CSV byte-for-byte; bundle its text for file:// use.
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const Data = require("../DH-FPA/data-model.js");
const filename = "2026-Wkly - FPA.csv";
const directory = path.join(__dirname, "../DH-FPA/data");
const bytes = fs.readFileSync(path.join(directory, filename));
const csv = bytes.toString("utf8");
const model = Data.readSource(csv, { name: filename });
const snapshot = { season: 2026, name: filename, sha256: crypto.createHash("sha256").update(bytes).digest("hex"), csv };
const output = "/* Generated by node scripts/sync-data.cjs. Edit the CSV, then regenerate. */\nwindow.FPA_SOURCE = " + JSON.stringify(snapshot).replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029") + ";\n";
fs.writeFileSync(path.join(directory, "2026-weekly.js"), output);
console.log(`Bundled ${model.audit.usedRows} matchup results across Weeks ${model.minWeek}–${model.maxWeek}; ${model.audit.excludedRows} rows have no opponent.`);
